### ISSUE TITLE
Getting an error "TypeError: a bytes-like object is required, not 'str'"

### ISSUE THREAD

**Issue by mady143** [Hynix07/Visual-Question-Answering#2]
Hi @Hynix07 ,

I am trying to run python train.py getting an error 
**"Traceback (most recent call last):
  File "train.py", line 43, in <module>
    if __name__ == '__main__':main()
  File "train.py", line 14, in main
    questions_train = prepare_data.get_questions_matrix('train')
  File "/home/manikantha/Downloads/VQAM/Visual-Question-Answering-master/prepare_data.py", line 67, in get_questions_matrix
    word_idx = ebd.load_idx()
  File "/home/manikantha/Downloads/VQAM/Visual-Question-Answering-master/embedding.py", line 15, in load_idx
    word_idx = pickle.load(file)
TypeError: a bytes-like object is required, not 'str'"**

i was unable to understand the error can you tell me how to resolve the issue,

Thanks & Regards,
Manikantha Sekhar...

**Comment by mady143** [comment]
Hi @Hynix07 ,
I am Closing this issue i resolved it by reading the file with binary format and encoding with **"encoding='latin1'"**
though i resolved this issue
